### ISSUE TITLE
Question about the output...

### ISSUE THREAD

**Issue by bapriddy** [ShadenSmith/splatt#34]
Can someone explain the output below??

```
splatt v2.0.0

Tensor information ---------------------------------------------
FILE=med.tns
DIMS=2425x10816x29567 NNZ=100000 DENSITY=1.289479e-07
COORD-STORAGE=3.05MB

MPI information ------------------------------------------------
DISTRIBUTION=MEDIUM DIMS=1x1x4
AVG NNZ=25000
MAX NNZ=25006  (0.02% diff)
AVG COMMUNICATION VOL=22531
MAX COMMUNICATION VOL=23352  (3.52% diff)

Factoring ------------------------------------------------------
NFACTORS=800 MAXITS=50 TOL=1.0e-05 REG=0.0e+00 RANKS=4 THREADS=1
CSF-ALLOC=TWOMODE TILE=NO
CSF-STORAGE=6.07MB FACTOR-STORAGE=396.64MB
```

**Comment by ShadenSmith** [comment]
Hi there,

The first block of information shows data on the tensor itself (the lengths of the modes, the number of non-zeros, etc.).

The second block of information provides information on how the tensor is distributed because it is being ran with MPI. In this case it is telling you it imposed a 1x1x4 decomposition on the tensor and gives you the load imbalance and communication volume (measured in number of rows sent or received).

The third block of information provides information on how the factorization is configured. So it says you are computing a rank 800 factorization using 4 MPI ranks, each with 1 thread.

FYI: the tensors packaged with SPLATT are useful for testing, but not necessarily other evaluations. I recommend you try out some of the tensors on [frostt.io](http://frostt.io/).

**Comment by bapriddy** [comment]
Thanks for the info!!
